[package]
name = "rust-tg-bot"
version = "0.1.0"
authors = ["Arden144 <general@ardensinclair.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
